### ISSUE TITLE
Code Conventions Mr. Sanderse

### ISSUE THREAD

**Issue by projojoboy** [PVB-Team-1/ProefProeveTeam1#17]
Reason: Mr. Sanderse did not listen to the code conventions made by the development team before the programming started. He listed the XML comments wrong by not using punctuation and spacing. This has slipped through to the development branch due to the terrible review of Mrs. Joseph. Though this can happen and is not seen as a big problem we rather have this prevented in the future.

**Comment by Vychron** [comment]
In my defense: i cannot check if code follows conventions that didn't exist at the time of reviewing.

**Comment by empireboy** [comment]
I changed the layout in the [Code Conventions](https://docs.google.com/document/d/1mqdmVkAOm5xLbfT_fNzorrzQRnzfXn5BnijzQosl1sE/edit) for a better overview.
