### ISSUE TITLE
Camera starts at the left dragging boundary instead of in the center

### ISSUE THREAD

**Issue by empireboy** [PVB-Team-1/ProefProeveTeam1#19]
As the title says, the camera needs to start at the center of the boundary. What happends now is when you start the game, you can only drag the camera to the right. You can drag it back aswell. So you need to be able to drag the camera to the left and right when the game starts.

The boundaries could be made relative to the start position of the camera.

**Comment by Vychron** [comment]
I made a [pull request](https://github.com/PVB-Team-1/ProefProeveTeam1/pull/24) with a fix similar to the zoom issue, which was indeed the boundaries not being relative to the start position of the camera.
