### ISSUE TITLE
Camera starts zoomed in

### ISSUE THREAD

**Issue by empireboy** [PVB-Team-1/ProefProeveTeam1#20]
As the title says, when the game starts you are zoomed in and you can only zoom out. This is supposed to be inverted.

**Comment by Vychron** [comment]
Thank you for bringing this up, without this issue I wouldn't have realized that I forgot to make the zoom boundaries relative to the camera's starting position.
A [pull request](https://github.com/PVB-Team-1/ProefProeveTeam1/pull/22) has been made with a fix to this issue.
