### ISSUE TITLE
Easier testing on pc

### ISSUE THREAD

**Issue by empireboy** [PVB-Team-1/ProefProeveTeam1#21]
It would be easier to test if we could drag the camera with the mouse aswell. Secondly we could add this for camera zooming. For camera zooming there could be 2 keyboard buttons to zoom in and out.

To only make this work on pc we could use this documentation for [platform dependent compilation](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html).

This would look something like this:
```
#if UNITY_ANDROID
      Debug.Log("This line of code is only compiled for android devices.");
 #endif

#if UNITY_STANDALONE_WIN
      Debug.Log("This line of code is only compiled for windows devices.");
 #endif
```

**Comment by Vychron** [comment]
A [pull request](https://github.com/PVB-Team-1/ProefProeveTeam1/pull/23) with platform dependent compiling for zooming controls has been created, one for scrolling will be added later.
